name: Nodejs Workflow


on:
   push:
      branches:
         - nodejs


jobs:
   build:
      runs-on: ubuntu-22.04
   
      steps:
         - name: Evaluate Commit Message
           run: |

            commitMessage="${{ github.event.head_commit.message }}";

            if [ "$commitMessage" != "Update" ]; then

               echo "Strictly told not to continue.";
               exit 1;
            
            else

               echo "Strictly told to continue.";
            
            fi
         
         - name: Checkout Code
           uses: actions/checkout@v2
         
         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
            node-version: 14
         
         - name: Install Dependencies
           run: npm install
         
         - name: Run Tests
           run: npm test
         
         - name: Evaluate lxRbckl Package Update
           run: |

            isSuccessful=$?;

            if [ $isSuccessful == 0 ]; then

               echo "Tests passed.";
            
            else

               echo "Tests failed.";
               exit 1;
            
            fi
         
         - name: Update Package
           run: npm publish
           env: 
            NODE_AUTH_TOKEN: ${{ secrets.NPM }}