name: NPM Workflow


on:
   push:
      branches:
         - NPM


jobs:
   build:
      runs-on: ubuntu-22.04
   
      steps:
         - name: Evaluate Commit Message
           run: |

            commitMessage="${{ github.event.head_commit.message }}";

            if [ "$commitMessage" != "Update" ]; then

               echo "Strictly told not to continue.";
               exit 1;
            
            fi
         
         - name: Checkout Code
           uses: actions/checkout@v4
         
         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
            node-version: '20.x'
         
         - name: Install Dependencies
           run: npm install
         
         - name: Create /dist
           run: mkdir dist
           

         - name: Run tsup
           run: npm run build

         - name: Initialize .npmrc File
           run: |
 
             echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMTOKEN }}" >> .npmrc;
             echo "//registry.npmjs.org/:username=${{ secrets.NPMUSERNAME }}" >> .npmrc;
             echo "//registry.npmjs.org/:_password=${{ secrets.NPMPASSWORD }}" >> .npmrc;
         
         - name: Update Package
           run: npm publish