name: Python Workflow


on:
   push:
      branches:
         - python


jobs:
   build:
      runs-on: ubuntu-22.04

      env:
         PYPI: ${{ secrets.PYPI }}
         PYGITHUB: ${{ secrets.PYGITHUB }}
      steps:
         - name: Evaluate Commit Message
           run: |

            commitMessage="${{ github.event.head_commit.message }}";

            if [ $commitMessage != "Update" ]; then

               echo "Strictly told not to advance.";
               exit 1;

            fi

         - name: Checkout Code
           uses: actions/checkout@v2
           with:
            ref: python
         
         - name: Setup Python 3.8
           uses: actions/setup-python@v2
           with:
            python-version: 3.8

         - name: Install Python Poetry
           run: pip install poetry
         
         - name: Install Poetry Environment
           run: poetry install

         - name: Run PyTest
           run: poetry run pytest

         - name: Evaluate lxRbckl Package Update
           run: |
            
            isSuccessful=$?;
            commitMessage="${{ github.event.head_commit.message }}";

            if [ $isSuccessful == 0 ] && [ $commitMessage == "Update" ]; then

               echo "Updating lxRbckl package."

               poetry config pypi-token.pypi $PYPI

               poetry build
               poetry publish
            
            else echo "Not updating lxRbckl package.";
            
            fi