name: Python Workflow


on:
   push:
      branches:
         - python


jobs:
   build:
      runs-on: ubuntu-22.04

      env:
         PYGITHUB: ${{ secrets.PYGITHUB }}

      steps:
         - name: Check Commit Message
           run: |

            if [ "${{github.event.head_commit.message}}" != "Test" ]; then

               echo "Strictly told not to execute PyTest.";
               exit 1;
            
            else echo "Executing PyTest.";

            fi

         - name: Checkout Code
           uses: actions/checkout@v2
           with:
            ref: python
         
         - name: Setup Python 3.8
           uses: actions/setup-python@v2
           with:
            python-version: 3.8
         
         - name: Install Dependencies
           run: pip install -r requirements.txt

         - name: Run PyTest
           run: pytest

         - name: Evaluate lxRbckl Package Update
           run: |
            
            isSuccessful=$?

            if [ $isSuccessful == 0 ]; then

               echo "We should upgrade package.";
            
            else echo "Do not upgrade package.";
            
            fi