name: Python Workflow


on:
   push:
      branches:
         - python


jobs:
   build:
      runs-on: ubuntu-22.04

      env:
         PYGITHUB: ${{ secrets.PYGITHUB }}

      steps:
         - name: checkout code
           uses: actions/checkout@v2
           with:
            ref: python