name: Python Workflow


on:
   push:
      branches:
         - python


jobs:
   build:
      runs-on: ubuntu-22.04

      env:
         PYPI: ${{ secrets.PYPI }}
         PYGITHUB: ${{ secrets.PYGITHUB }}
      steps:
         - name: Check Commit Message
           run: |

            if [ "${{ github.event.head_commit.message }}" != "Test" ]; then

               echo "Strictly told not to execute PyTest.";
               exit 1;
            
            else echo "Executing PyTest.";

            fi

         - name: Checkout Code
           uses: actions/checkout@v2
           with:
            ref: python
         
         - name: Setup Python 3.8
           uses: actions/setup-python@v2
           with:
            python-version: 3.8

         - name: Install Python Poetry
           run: pip install poetry
         
         - name: Initialize Poetry Environment
           run: poetry install

         - name: Run PyTest
           run: poetry run pytest

         - name: Evaluate lxRbckl Package Update
           run: |
            
            isSuccessful=$?;
            commitMessage="${{ github.event.head_commit.message }}";

            if [ $isSuccessful == 0 ] && [ commitMessage == "Update" ]; then

               echo "Condition met to update package."

               poetry config pypi-token.pypi $PYPI

               poetry build
               poetry publish
            
            else echo "Condition not met to update package.";
            
            fi